### ISSUE TITLE
Suggestion: Increment version

### ISSUE THREAD

**Issue by DavidMikeSimon** [MestreLion/wavegain#3]
@MestreLion Since 1.3.1, you've added a number of really critical improvements; in particular, the issue with temporary file names tripped me up when using that version, and is now corrected in your master. Since your code has been stable for a while, could you increment the version number to encourage distro maintainers to use it?

**Comment by MestreLion** [comment]
Thanks for the compliments, but until issue #2 is fixed I'd rather not encourage anyone to use this port.

**Comment by AliceWonderMiscreations** [comment]
Just some encouragement, this tool is very useful to me - I do not use it to modify wave files so issue #2 is not an issue for me. But thank you for this tool.

I decode lossy files to 32-bit float wave and then use this tool to get accurate ReplayGain data to add to Matroska containers that have the audio, not positive I am calculating the peak tag correctly but I think I am. Anyway thank you.

I am packaging it for my CentOS 7 media package repository, I will put a warning in the package description regarding issue #2 to prevent possible disaster.

And if I have time, I will look into maybe doing the man page thing mentioned in the TODO file :)

**Comment by MestreLion** [comment]
Fixed, check the new 1.3.1-1 tag!
